### ISSUE TITLE
[Bug] [1.15.2] [1.1] Crashes on startup of dedicated server

### ISSUE THREAD

**Issue by sandalle** [kgasiorowski/nether_ores#3]
## Versions
Minecraft: 1.15.2
Forge: 1.15.2-31.1.18
Nether Ores: 1.1
Java version: 1.8.0_241 on Linux x86_64 (Linux Mint 19.3)
crash report: [crash-2020-03-09_19.25.51-server.txt](https://github.com/kubas-nether-ores/nether-ores/files/4308761/crash-2020-03-09_19.25.51-server.txt)

## Error
In logs/latest.log I have this **FATAL** error when nether_ores.jar is enabled:
```
[19:25:51] [Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[19:25:51] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Nether ores (nether_ores) encountered an error during the common_setup event phase
§7javafx/util/Pair
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:154) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:46) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241] {}
```

Seems to load fine on a client (OS X Mojave (10.14.6) with java 1.8.0_241) and single-player world.

**Comment by kgasiorowski** [comment]
@sandalle Is this the entire error readout? Or is there more you didn't include?

**Comment by sandalle** [comment]
@kgasiorowski I've attached the crash report, sorry about missing it. :)

**Comment by kgasiorowski** [comment]
Oh, thanks! Sorry if I missed it. I'll look into this. Thanks again.

**Comment by sandalle** [comment]
You didn't miss it, I didn't attach it (until you asked). ;)
